package com.starwars.controller;

import io.swagger.v3.oas.annotations.Hidden;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.CrossOrigin;

import java.util.HashMap;
import java.util.Map;

@Hidden
@RestController
@CrossOrigin(origins = "*")
public class HomeController {

    @GetMapping(value = "/", produces = MediaType.TEXT_HTML_VALUE)
    public String getHomePage() {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>");
        html.append("<html lang=\"es\">");
        html.append("<head>");
        html.append("    <meta charset=\"UTF-8\">");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        html.append("    <title>Star Wars API - Challenge Técnico Conexa</title>");
        html.append("    <style>");
        html.append("        * {");
        html.append("            margin: 0;");
        html.append("            padding: 0;");
        html.append("            box-sizing: border-box;");
        html.append("        }");
        html.append("        ");
        html.append("        body {");
        html.append("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        html.append("            background: linear-gradient(135deg, #0f0f23 0%, #1a1a2e 50%, #16213e 100%);");
        html.append("            color: #ffffff;");
        html.append("            line-height: 1.6;");
        html.append("            min-height: 100vh;");
        html.append("        }");
        html.append("        ");
        html.append("        .container {");
        html.append("            max-width: 1200px;");
        html.append("            margin: 0 auto;");
        html.append("            padding: 2rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .header {");
        html.append("            text-align: center;");
        html.append("            margin-bottom: 3rem;");
        html.append("            padding: 2rem 0;");
        html.append("            border-bottom: 2px solid #ffd700;");
        html.append("        }");
        html.append("        ");
        html.append("        .header h1 {");
        html.append("            font-size: 3rem;");
        html.append("            margin-bottom: 1rem;");
        html.append("            color: #ffd700;");
        html.append("            text-shadow: 2px 2px 4px rgba(0,0,0,0.5);");
        html.append("        }");
        html.append("        ");
        html.append("        .header p {");
        html.append("            font-size: 1.2rem;");
        html.append("            color: #b8b8b8;");
        html.append("            max-width: 600px;");
        html.append("            margin: 0 auto;");
        html.append("        }");
        html.append("        ");
        html.append("        .content {");
        html.append("            display: grid;");
        html.append("            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));");
        html.append("            gap: 2rem;");
        html.append("            margin-bottom: 3rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .card {");
        html.append("            background: rgba(255, 255, 255, 0.1);");
        html.append("            border-radius: 15px;");
        html.append("            padding: 2rem;");
        html.append("            border: 1px solid rgba(255, 215, 0, 0.3);");
        html.append("            backdrop-filter: blur(10px);");
        html.append("            transition: transform 0.3s ease, box-shadow 0.3s ease;");
        html.append("        }");
        html.append("        ");
        html.append("        .card:hover {");
        html.append("            transform: translateY(-5px);");
        html.append("            box-shadow: 0 10px 30px rgba(255, 215, 0, 0.2);");
        html.append("        }");
        html.append("        ");
        html.append("        .card h3 {");
        html.append("            color: #ffd700;");
        html.append("            margin-bottom: 1rem;");
        html.append("            font-size: 1.5rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .card p {");
        html.append("            color: #b8b8b8;");
        html.append("            margin-bottom: 1rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .btn {");
        html.append("            display: inline-block;");
        html.append("            padding: 0.8rem 1.5rem;");
        html.append("            background: linear-gradient(45deg, #ffd700, #ffed4e);");
        html.append("            color: #0f0f23;");
        html.append("            text-decoration: none;");
        html.append("            border-radius: 25px;");
        html.append("            font-weight: bold;");
        html.append("            transition: all 0.3s ease;");
        html.append("            border: none;");
        html.append("            cursor: pointer;");
        html.append("            font-size: 1rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .btn:hover {");
        html.append("            transform: scale(1.05);");
        html.append("            box-shadow: 0 5px 15px rgba(255, 215, 0, 0.4);");
        html.append("        }");
        html.append("        ");
        html.append("        .btn-secondary {");
        html.append("            background: linear-gradient(45deg, #4a90e2, #357abd);");
        html.append("            color: white;");
        html.append("        }");
        html.append("        ");
        html.append("        .endpoints {");
        html.append("            background: rgba(255, 255, 255, 0.05);");
        html.append("            border-radius: 15px;");
        html.append("            padding: 2rem;");
        html.append("            margin-top: 2rem;");
        html.append("            border: 1px solid rgba(255, 215, 0, 0.2);");
        html.append("        }");
        html.append("        ");
        html.append("        .endpoints h3 {");
        html.append("            color: #ffd700;");
        html.append("            margin-bottom: 1rem;");
        html.append("            text-align: center;");
        html.append("        }");
        html.append("        ");
        html.append("        .endpoint-list {");
        html.append("            display: grid;");
        html.append("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));");
        html.append("            gap: 1rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .endpoint-item {");
        html.append("            background: rgba(255, 255, 255, 0.1);");
        html.append("            padding: 1rem;");
        html.append("            border-radius: 8px;");
        html.append("            border-left: 4px solid #ffd700;");
        html.append("        }");
        html.append("        ");
        html.append("        .endpoint-item strong {");
        html.append("            color: #ffd700;");
        html.append("            display: block;");
        html.append("            margin-bottom: 0.5rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .endpoint-item code {");
        html.append("            background: rgba(0, 0, 0, 0.3);");
        html.append("            padding: 0.2rem 0.5rem;");
        html.append("            border-radius: 4px;");
        html.append("            font-family: 'Courier New', monospace;");
        html.append("            color: #4a90e2;");
        html.append("        }");
        html.append("        ");
        html.append("        .footer {");
        html.append("            text-align: center;");
        html.append("            margin-top: 3rem;");
        html.append("            padding: 2rem 0;");
        html.append("            border-top: 1px solid rgba(255, 215, 0, 0.3);");
        html.append("            color: #b8b8b8;");
        html.append("        }");
        html.append("        ");
        html.append("        .footer-buttons {");
        html.append("            margin: 1rem 0;");
        html.append("        }");
        html.append("        ");
        html.append("        .footer-btn {");
        html.append("            display: inline-block;");
        html.append("            padding: 0.6rem 1.2rem;");
        html.append("            margin: 0 0.5rem;");
        html.append("            background: rgba(255, 215, 0, 0.2);");
        html.append("            color: #ffd700;");
        html.append("            text-decoration: none;");
        html.append("            border-radius: 20px;");
        html.append("            border: 1px solid rgba(255, 215, 0, 0.3);");
        html.append("            transition: all 0.3s ease;");
        html.append("            font-size: 0.9rem;");
        html.append("        }");
        html.append("        ");
        html.append("        .footer-btn:hover {");
        html.append("            background: rgba(255, 215, 0, 0.3);");
        html.append("            transform: translateY(-2px);");
        html.append("        }");
        html.append("        ");
        html.append("        .footer a {");
        html.append("            color: #ffd700;");
        html.append("            text-decoration: none;");
        html.append("        }");
        html.append("        ");
        html.append("        .footer a:hover {");
        html.append("            text-decoration: underline;");
        html.append("        }");
        html.append("        ");
        html.append("        @media (max-width: 768px) {");
        html.append("            .container {");
        html.append("                padding: 1rem;");
        html.append("            }");
        html.append("            ");
        html.append("            .header h1 {");
        html.append("                font-size: 2rem;");
        html.append("            }");
        html.append("            ");
        html.append("            .content {");
        html.append("                grid-template-columns: 1fr;");
        html.append("            }");
        html.append("        }");
        html.append("    </style>");
        html.append("</head>");
        html.append("<body>");
        html.append("    <div class=\"container\">");
        html.append("        <div class=\"header\">");
        html.append("            <h1>🌟 Star Wars API</h1>");
        html.append("            <p>API REST que integra con la API oficial de Star Wars (swapi.tech) y proporciona un sistema de autenticación con JWT</p>");
        html.append("        </div>");
        html.append("        ");
        html.append("        <div class=\"content\">");
        html.append("            <div class=\"card\">");
        html.append("                <h3>📚 Documentación Interactiva</h3>");
        html.append("                <p>Accede a Swagger UI para probar todos los endpoints de la API de manera interactiva.</p>");
        html.append("                <a href=\"/swagger-ui/index.html\" class=\"btn\">Abrir Swagger UI</a>");
        html.append("            </div>");
        html.append("            ");
        html.append("            <div class=\"card\">");
        html.append("                <h3>📖 Documentación Técnica</h3>");
        html.append("                <p>Accede al repositorio de GitHub para ver el código fuente, README completo y documentación técnica detallada.</p>");
        html.append("                <a href=\"https://github.com/maxif96/conexa-starwars-challenge\" target=\"_blank\" class=\"btn btn-secondary\">Ver en GitHub</a>");
        html.append("            </div>");
        html.append("        </div>");
        html.append("        ");
        html.append("        <div class=\"endpoints\">");
        html.append("            <h3>🚀 Endpoints Principales</h3>");
        html.append("            <div class=\"endpoint-list\">");
        html.append("                                <div class=\"endpoint-item\">");
        html.append("                    <strong>Autenticación</strong>");
        html.append("                    <code>POST /auth/login</code><br>");
        html.append("                    <code>POST /auth/register</code><br>");
        html.append("                    <code>GET /auth/check-username/{username}</code>");
        html.append("                </div>");
        html.append("                <div class=\"endpoint-item\">");
        html.append("                    <strong>Personajes</strong>");
        html.append("                    <code>GET /people</code><br>");
        html.append("                    <code>GET /people/{id}</code><br>");
        html.append("                    <code>GET /people?name={name}&page={page}&limit={limit}</code>");
        html.append("                </div>");
        html.append("                <div class=\"endpoint-item\">");
        html.append("                    <strong>Películas</strong>");
        html.append("                    <code>GET /films</code><br>");
        html.append("                    <code>GET /films/{id}</code><br>");
        html.append("                    <code>GET /films?name={name}&page={page}&limit={limit}</code>");
        html.append("                </div>");
        html.append("                <div class=\"endpoint-item\">");
        html.append("                    <strong>Naves Espaciales</strong>");
        html.append("                    <code>GET /starships</code><br>");
        html.append("                    <code>GET /starships/{id}</code><br>");
        html.append("                    <code>GET /starships?name={name}&page={page}&limit={limit}</code>");
        html.append("                </div>");
        html.append("                <div class=\"endpoint-item\">");
        html.append("                    <strong>Vehículos</strong>");
        html.append("                    <code>GET /vehicles</code><br>");
        html.append("                    <code>GET /vehicles/{id}</code><br>");
        html.append("                    <code>GET /vehicles?name={name}&page={page}&limit={limit}</code>");
        html.append("                </div>");
        html.append("            </div>");
        html.append("        </div>");
        html.append("        ");
        html.append("        <div class=\"footer\">");
        html.append("            <p>Desarrollado por <a href=\"https://github.com/maxif96\" target=\"_blank\">Maximiliano Ariel Falcone</a> para el Challenge Técnico Conexa</p>");
        html.append("            <div class=\"footer-buttons\">");
        html.append("                <a href=\"https://github.com/maxif96/conexa-starwars-challenge\" target=\"_blank\" class=\"footer-btn\">📖 Ver en GitHub</a>");
        html.append("                <a href=\"https://github.com/maxif96/conexa-starwars-challenge/blob/main/README.md\" target=\"_blank\" class=\"footer-btn\">📚 README Completo</a>");
        html.append("                <a href=\"/api\" class=\"footer-btn\">🔧 API Info</a>");
        html.append("            </div>");
        html.append("        </div>");
        html.append("    </div>");
        html.append("</body>");
        html.append("</html>");
        
        return html.toString();
    }

    @GetMapping("/api")
    public ResponseEntity<Map<String, Object>> getApiInfo() {
        Map<String, Object> apiInfo = new HashMap<>();
        apiInfo.put("name", "Star Wars API");
        apiInfo.put("description", "API REST que integra con la API oficial de Star Wars (swapi.tech) y proporciona un sistema de autenticación con JWT");
        apiInfo.put("version", "1.0.0");
        apiInfo.put("author", "Maxif96");
        apiInfo.put("github", "https://github.com/maxif96");
        
        Map<String, String> endpoints = new HashMap<>();
        endpoints.put("swagger_ui", "/swagger-ui/index.html");
        endpoints.put("api_docs", "/api-docs");
        endpoints.put("authentication", "/auth");
        endpoints.put("people", "/people");
        endpoints.put("films", "/films");
        endpoints.put("starships", "/starships");
        endpoints.put("vehicles", "/vehicles");
        
        apiInfo.put("endpoints", endpoints);
        
        Map<String, String> documentation = new HashMap<>();
        documentation.put("swagger_ui", "Interfaz interactiva para probar la API");
        documentation.put("readme", "https://github.com/maxif96/starwars-api/blob/main/README.md");
        
        apiInfo.put("documentation", documentation);
        
        return ResponseEntity.ok(apiInfo);
    }
}
